version: '2.1'
services:
  unreads-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      USERS_MS_URL: '192.168.99.100'
      USERS_MS_PORT: '3000'
      USERS_MS_ENTRY: 'users'

      BOOKLIST_URL: '192.168.0.10'
      BOOKLIST_PORT: '3001'
      BOOKLIST_ENTRY: 'api/v1'

      BOOKS_MS_URL: '192.168.99.100'
      BOOKS_MS_PORT: '3002'
      BOOKS_MS_ENTRY: 'books-ms'
    ports:
      - '5000:5000'